### ISSUE TITLE
Random exception thrown

### ISSUE THREAD

**Issue by JemarJones** [slackhq/python-rtmbot#47]
After running for an unkown number of hours this exception was thrown, any insight?

```
Traceback (most recent call last):
  File "./rtmbot.py", line 24, in <module>
    bot.start()
  File "/Users/jemarjones/Documents/Projects/MarsBot/rtmbot/core.py", line 78, in start
    self._start()
  File "/Users/jemarjones/Documents/Projects/MarsBot/rtmbot/core.py", line 65, in _start
    for reply in self.slack_client.rtm_read():
  File "/usr/local/lib/python2.7/site-packages/slackclient/_client.py", line 39, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/usr/local/lib/python2.7/site-packages/slackclient/_server.py", line 110, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 298, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 315, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 328, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 360, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python2.7/site-packages/websocket/_abnf.py", line 312, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python2.7/site-packages/websocket/_abnf.py", line 261, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python2.7/site-packages/websocket/_abnf.py", line 346, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 429, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python2.7/site-packages/websocket/_socket.py", line 77, in recv
    bytes = sock.recv(bufsize)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
socket.error: [Errno 60] Operation timed out
```

**Comment by jammons** [comment]
Hmm... I'd guess that the internet connection got lost and the connection to the websocket broke. This is more an issue for https://github.com/slackhq/python-slackclient, which maintains the websocket connection. 

I will eventually get to working on that repo and cleaning it up some. If you find a way to reliably reproduct this error message, I'd love it if you could create another issue over on that repo to track it.

Thanks!

**Comment by JemarJones** [comment]
If the connection is momentarily lost, does the connection permanently close? As in it doesn't attempt to reconnect?

**Comment by jammons** [comment]
Ok, I just verified this by starting rtmbot.py then cutting off my wifi connection. It took about 60-120 seconds (I didn't time it) to time out like your stacktrace above.

As of right now, the slackclient code doesn't handle this scenario gracefully. In the future I'm hoping we'll add some intelligent reconnection logic, but as of right now, it won't reconnect after it has timed out. (It will work however if you re-establish a connection prior to the timeout.

**Comment by JemarJones** [comment]
Okay, can you point me to the correct place in python-slackclient that would need to be modified?

**Comment by jammons** [comment]
I can certainly try :) -- I'm not very familiar with it, but looking at your stack trace, it looks like this line is where it's trying to read from the websocket and then erroring out: https://github.com/slackhq/python-slackclient/blob/master/slackclient/_server.py#L110.

You may take a look around for other examples of how people have handled websocket connections and timeouts/disconnects. Here's a few examples I just found: https://stackoverflow.com/questions/23980962/implementing-and-testing-websocket-server-connection-timeout

**Comment by cmaliwal** [comment]
facing the same issue :  


```
File "app.py", line 129, in <module>
    command, channel, user = parse_bot_commands(slack_client.rtm_read())
  File "/usr/local/lib/python3.5/site-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/usr/local/lib/python3.5/site-packages/slackclient/server.py", line 278, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/usr/local/lib/python3.5/site-packages/websocket/_core.py", line 302, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.5/site-packages/websocket/_core.py", line 319, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.5/site-packages/websocket/_core.py", line 332, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.5/site-packages/websocket/_core.py", line 366, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.5/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.5/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.5/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.5/site-packages/websocket/_core.py", line 441, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.5/site-packages/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/local/lib/python3.5/ssl.py", line 922, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.5/ssl.py", line 585, in read
    v = self._sslobj.read(len)
TimeoutError: [Errno 110] Operation timed out
```

**Comment by abi98213** [comment]
Facing the same issue
